name: registry_pull
description: "app to record my calisthenics workouts."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.5.0+8

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  routefly: ^2.0.4
  asp: ^2.0.3
  auto_injector: ^2.0.5
  brasil_datetime: ^0.3.2
  path_provider: ^2.1.4
  localstore: ^1.4.0
  provider: ^6.1.1
  intl: ^0.19.0
  win32: ^5.12.0
  json_annotation: ^4.8.1
  flutter_localizations:
    sdk: flutter
  upgrader: ^11.4.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.13
  equatable: ^2.0.5
  mocktail: ^1.0.3
  icons_launcher: ^2.1.7
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.6.0


icons_launcher:
  image_path: "assets/icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android_12:
    image: assets/splash.png
    color: "#FFFFFF"
flutter:
  generate: true

  uses-material-design: true

  assets:
    - ./assets/muscle/arm.png
    - ./assets/muscle/leg.png
    - ./assets/muscle/back.png
    - ./assets/muscle/chest.png

  fonts:
    - family: Roboto
      fonts:
        - asset: ./assets/fonts/Roboto-Regular.ttf
